### ISSUE TITLE
Weird rendering in the Networks Section

### ISSUE THREAD

**Issue by albertov19** [papermoonio/polkadot-mkdocs#39]
Just noticed there is a weird rendering of the right-hand side nav bar in the networks section and dev pathways (seems to be root level?): 
![image](https://github.com/user-attachments/assets/861f5828-9072-45cf-bd14-f0101117e41f)

![image](https://github.com/user-attachments/assets/a026c35c-d9d9-4f94-9c2c-0a02b9287d90)

**Comment by eshaben** [comment]
This was addressed in #41
